### ISSUE TITLE
Kinect V2 Runtime Version 2.2

### ISSUE THREAD

**Issue by lubocode** [SirLynix/obs-kinect#12]
Just wanted to let you know that there is a newer version of the KinectV2 runtime.
The link:
https://www.microsoft.com/en-us/download/details.aspx?id=100067

**Comment by SirLynix** [comment]
Thanks! I will update the readme with this link.

I couldn't find an associated 2.2 SDK though.

**Comment by lubocode** [comment]
Me neither 😅
Got the link from reddit, when I had problems setting up the Kinect. https://www.reddit.com/r/kinect/comments/g3hpzm/windows_10_tipstricks_for_using_kinect_v2_as_a/
