### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by sew3521** [SirLynix/obs-kinect#17]
This plugin is very useful and I was wondering if you had a way for people who enjoy the plugin to send you a donation/tip to thank you for your hard work.

**Comment by SirLynix** [comment]
Hi again.

You can donate through GitHub sponsor/PayPal using the sponsor button above.

Thanks a lot for wanting to support me! 😀

**Comment by sew3521** [comment]
Thanks. I somehow missed that button. It is not much but I hope it shows my appreciation for this plugin.

**Comment by SirLynix** [comment]
I just wanted to say a big thank you to the people who donated for this project, since multiple people did it when this issue opened. Much merci to you!
