### ISSUE TITLE
Body & depth glitches sometimes?

### ISSUE THREAD

**Issue by marv3lls** [SirLynix/obs-kinect#20]
I've gotten it where just depth will render my close body pretty well but Body & Depth sometimes puts a body up and to the left of where I am? I'd love to fork and help ya play with this stuff, it's just been a long time since I developed for Windows more than PHP lmao.
![image](https://user-images.githubusercontent.com/202692/83202606-c70de200-a0fc-11ea-88d2-7dd88b246528.png)

**Comment by marv3lls** [comment]
Ah, also important, it only turns on when I set depth delay frames to one.

**Comment by SirLynix** [comment]
This seems to be a bug with the CPU depth mapping. Could you confirm it also happen when unchecking "GPU depth-mapping"? I'm looking at it.

**Comment by SirLynix** [comment]
Found and fixed, the fix will be available in 0.3 RC3 (which should be the last one before 0.3 release).
Thank you for the report.
