### ISSUE TITLE
Kinect source in OBS

### ISSUE THREAD

**Issue by Jenko1** [SirLynix/obs-kinect#39]
Hi All, I have downloaded all files to use my Kinect as webcam/green screen in obs. i have copied the files over to obs-studio on my C drive, unfortunately when I open OBS their is no Kinect source when I goto add a new source.

Worked on my other laptop but unfortunately the graphic's card isn't good enough hence why I tried on the new laptop.

Any ideas would be most apricated.
![OBS sources](https://user-images.githubusercontent.com/74275445/98749447-97554c80-23b3-11eb-8870-7319c3419db8.jpg)

**Comment by SirLynix** [comment]
Did you install [Visual Studio 2019 redistributables](https://aka.ms/vs/16/release/vc_redist.x64.exe)? See the FAQ : [I copied the files and the source doesn't show up](https://github.com/SirLynix/obs-kinect#i-copied-the-files-and-the-source-doesnt-show-up).

**Comment by Jenko1** [comment]
Thank you for your reply. Download and all now working great. Thanks again.
