### ISSUE TITLE
Support for IR webcams

### ISSUE THREAD

**Issue by MatthewCash** [SirLynix/obs-kinect#4]
I am wondering if it would be possible to use IR/Windows Hello webcams instead of a Kinect for this since they use a similar technology. I know that it is possible to use a Kinect as an IR camera, but I cannot find an easy way to do it the other way around.

**Comment by SirLynix** [comment]
Hello.

I would love to add support for other IR webcams, but the problem is I have no idea on how to support this, do you know about some kind of library allowing that?

**Comment by SirLynix** [comment]
Closed for no reply
