### ISSUE TITLE
Kinect doesn't activate in portable mode

### ISSUE THREAD

**Issue by VeGas-Gh0st** [SirLynix/obs-kinect#41]
in regular obs the plugin works fine, but in portable mode i cant get the camera to activate even in admin mode.

Normal version
![2020-12-08 12_03_27-Photos](https://user-images.githubusercontent.com/15202802/101548975-b1a62a00-3961-11eb-89d4-a0b87cdacb23.jpg)
 

Portable version
![2020-12-08 12_01_49-OBS 26 0 0-4-g37075a81 (64-bit, windows) - Portable Mode - Profile_ Defualty - S](https://user-images.githubusercontent.com/15202802/101549019-c7b3ea80-3961-11eb-8330-ac30ca9e1065.jpg)

**Comment by SirLynix** [comment]
This is weird since I run all my tests in portable mode without any issue.

What does the logs say?
Have you tried with the last release (0.3RC2)?

**Comment by VeGas-Gh0st** [comment]
ok did more testing, v3 overwrote something im thinking as this one now works fine.

![2020-12-08 15_55_31-OBS 26 0 0-4-g37075a81 (64-bit, windows) - Portable Mode - Profile_ Defualty - S](https://user-images.githubusercontent.com/15202802/101555722-0b145600-396e-11eb-95f4-dbca0c3f3871.jpg)

Issue resolved it seems, thank you for your quick response.

**Comment by SirLynix** [comment]
After looking a bit closer it seems you were having 0.3 in normal mode and 0.2 in portable mode. As you're using a KinectV1 only 0.3 does support it.

I know 0.3 is kinda WIP for now but what issues are you talking about?

**Comment by SirLynix** [comment]
Closed for no answer.
