### ISSUE TITLE
Control Brightness, Hue, or Gain

### ISSUE THREAD

**Issue by Wolfhound905** [SirLynix/obs-kinect#58]
If possible could you add the ability to adjust the brightness/iso of the Kinect via the SDK? I try to use the filter in obs but since the Kinect itself is too bright the data is gone so I can't just lower brightness.

![image](https://user-images.githubusercontent.com/58155937/138186699-d32541be-7969-47f8-abf7-c6b93021fee6.png)

**Comment by SirLynix** [comment]
Hi,

What version of obs-kinect are you using and what Kinect do you have?

Nightlies versions of obs-kinect have color control available for all Kinect models that support it

**Comment by Wolfhound905** [comment]
Do you know a way I can adjust the exposure on the sensor level? Because adjusting it with OBS controls is useless because the overexposed areas are just white, there is no data there.

**Comment by SirLynix** [comment]
With the last obs-kinect version you should be able to change the exposure of all Kinect sensors, directly from the obs-kinect source.
