### ISSUE TITLE
Kinect not found in device list 

### ISSUE THREAD

**Issue by JawShoeAaa** [SirLynix/obs-kinect#63]
No matter how many times i refresh the list my working, plugged in and connected Kinect isn't displayed on OBS for me to select , it can however function in the SDK Browser on any of it's programs, and I've copied both folders into my OBS and been sure to restart

Can anyone assist in this problem with OBS

**Comment by SirLynix** [comment]
Hi.
Could you show me your OBS logs?

**Comment by JawShoeAaa** [comment]
![OBS 2022-04-09](https://user-images.githubusercontent.com/94025447/162567535-1cdec8e6-4120-4d58-9b9b-1d93e875c9ff.png)
like this?

**Comment by SirLynix** [comment]
No, I mean OBS text logs, you can access them with the Help menu (Help => Log files => Show log files)

**Comment by JawShoeAaa** [comment]
[2022-04-09 02-21-57.txt](https://github.com/SirLynix/obs-kinect/files/8456691/2022-04-09.02-21-57.txt)
like this then?

**Comment by SirLynix** [comment]
Yes, and it shows the issue:
```
02:22:01.675: LoadLibrary failed for 'obs-kinect-azuresdk': The specified module could not be found.
02:22:01.675:  (126)
02:22:01.675: LoadLibrary failed for 'obs-kinect-freenect': The specified module could not be found.
02:22:01.675:  (126)
02:22:01.676: LoadLibrary failed for 'obs-kinect-freenect2': The specified module could not be found.
02:22:01.676:  (126)
02:22:01.677: LoadLibrary failed for 'obs-kinect-sdk10': The specified module could not be found.
02:22:01.677:  (126)
02:22:01.677: LoadLibrary failed for 'obs-kinect-sdk20': The specified module could not be found.
02:22:01.677:  (126)
```

How did you install obs-kinect? You're supposed to copy every file at the right location, not just the plugin folder.

**Comment by JawShoeAaa** [comment]
i copied the two folders into my obs folder, how do i fix it?

**Comment by SirLynix** [comment]
there are 3 folders: `bin`, `data` and `obs-plugins`, copy them to your obs installation

**Comment by JawShoeAaa** [comment]
when i did that it found new files to copy, when i restarted OBS it works now
