### ISSUE TITLE
[Small issue] LED Light blinks when on standby

### ISSUE THREAD

**Issue by FaxMac** [SirLynix/obs-kinect#68]
When I use my Kinect V1 in OBS, the standby green LED keeps blinking, is there a way to make it perma on/off? It's distracting (and i'm out of electical tape)

**Comment by SirLynix** [comment]
Hi, it should be just on when in use and shouldn't blink. Does it blink also with official Microsoft examples?

**Comment by delet-1** [comment]
The Xbox 360 version of the V1 always blinks when connected to a PC, even when it's in use and functioning correctly.

**Comment by SirLynix** [comment]
Oh, I didn't know that. I have the Kinect for Windows version which doesn't blink.

I'll add it to the readme, thanks for the info.
