### ISSUE TITLE
Kinect V2. Not showing on OBS.

### ISSUE THREAD

**Issue by rjkatz** [SirLynix/obs-kinect#85]
I downloaded the OBS add on along with installing all that was asked for X Box One V2 Kinect on Windows 11 and it still does not detect it in OBS but PC is able to run it. Here are screenshots to help.
<img width="398" alt="image" src="https://github.com/SirLynix/obs-kinect/assets/10516327/86ec58f1-c758-4397-b9a3-b7d774d320d8">
<img width="660" alt="image" src="https://github.com/SirLynix/obs-kinect/assets/10516327/fe193b72-551a-4224-9689-ecb4be63a96a">
<img width="1490" alt="image" src="https://github.com/SirLynix/obs-kinect/assets/10516327/b0b3af99-2a39-4063-97e6-5e756fe194c9">

**Comment by SirLynix** [comment]
Hi!

Could you check the logs of OBS?

**Comment by rjkatz** [comment]
Sure. Here you go 
[2023-09-22 17-09-21.txt](https://github.com/SirLynix/obs-kinect/files/12704616/2023-09-22.17-09-21.txt)

**Comment by SirLynix** [comment]
```
LoadLibrary failed for 'obs-kinect-sdk20': The specified module could not be found.
17:09:23.488:  (126)
```
this is the problem, it cannot load the Kinect 2 backend, either because the dll is missing (did you copy all files to tour obs installation?) or because a dependency is missing (did you install the Kinect runtime and VS redis from the [readme](https://github.com/SirLynix/obs-kinect#how-to-use-for-end-users-you-probably-want-this)?)

**Comment by rjkatz** [comment]
I have the sdk installed. So which dll file should I have on there?
<img width="650" alt="image" src="https://github.com/SirLynix/obs-kinect/assets/10516327/4649d54f-33c1-4809-abb2-7dc5a7e106cf">


I have the plugins folder shown here. If not let me know where it should be located.

<img width="572" alt="image" src="https://github.com/SirLynix/obs-kinect/assets/10516327/f0e017d9-bc22-4894-aac9-8849e2906c06">

**Comment by rjkatz** [comment]
dll is in the obs 64bit folder location 

<img width="845" alt="image" src="https://github.com/SirLynix/obs-kinect/assets/10516327/9a10a19f-a31c-410a-a050-c489d32ed974">

**Comment by rjkatz** [comment]
Reinstalled the Files. Works fine now. Thank you!
