### ISSUE TITLE
Compilation error (LibObs not found)

### ISSUE THREAD

**Issue by SirLynix** [SirLynix/obs-kinect#93]
Hi there, sorry I am an OBS noob. I have the following issue on my machines (mac and arch linux), I am assuming have skipped a very obvious step, please help.

```
obs-kinect on  master via 🌙 v5.4.6
❯ xmake build
error: ./xmake.lua:120: attempt to index a nil value (global 'LibObs')
stack traceback:
    [./xmake.lua:120]: in main chunk

checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
error: ./xmake.lua:120: attempt to index a nil value (global 'LibObs')
stack traceback:
    [./xmake.lua:120]: in main chunk
```

_Originally posted by @djpiper28 in https://github.com/SirLynix/obs-kinect/issues/9#issuecomment-2060695394_

**Comment by SirLynix** [comment]
@djpiper28 I moved your question here to try to keep #9 minimal.

However it seems you're missing the creation of config.lua, you need to duplicate [config.lua.default](https://github.com/SirLynix/obs-kinect/blob/master/config.lua.default) to config.lua and tell it where obs lies.

**Comment by djpiper28** [comment]
> @djpiper28 I moved your question here to try to keep #9 minimal.
> 
> However it seems you're missing the creation of config.lua, you need to duplicate [config.lua.default](https://github.com/SirLynix/obs-kinect/blob/master/config.lua.default) to config.lua and tell it where obs lies.

This worked, I must have missed it in the README. Thanks for your help.
